#!/usr/bin/env python
# coding: utf-8

# In[3]:


#python data type
x = 2
y = 2.8
z = 2+3j
print(x)
print(y)
print(z)
print(type(x))
print(type(y))
print(type(z))



# In[4]:


x = 234
y = 34567890
z = 49875
print(x)
print(y)
print(z)
print(type(x))
print(type(y))
print(type(z))





# In[6]:


x = 2.8
y = 3.0
z = -35.67
print(x)
print(y)
print(z)
print(type(x))
print(type(y))
print(type(z))


# In[10]:


x = 28j
y = 3j
z = -5j
print(x)
print(y)
print(z)
print(type(x))
print(type(y))
print(type(z))


# In[11]:


x = int(2)
y = int(2.9)
z = int("3")
print(x)
print(y)
print(z)
print(type(x))
print(type(y))
print(type(z))


# In[13]:


x = float(2)
y = float(2.9)
z = float("3")
w = float("4.2")
print(x)
print(y)
print(z)
print(w)
print(type(x))
print(type(y))
print(type(z))
print(type(w))


# In[14]:


x = str("s")
y = str(29)
z = str("3")
w = str(3.0)
print(x)
print(y)
print(z)
print(w)
print(type(x))
print(type(y))
print(type(z))
print(type(w))


# In[15]:


x = 2
y = 2.8
z = 2+3j
print(x)
print(y)
print(z)
print(type(x))
print(type(y))
print(type(z))



# In[16]:


x = 1         #int
y = 3.9       # float
z = 4+1j      #complex

# convert from int to float :
a = float(x)

# convert from float to int :
a = int(y)

# convert from int to complex :
a = complex(z)

print(x)
print(y)
print(z)

print(type(x))
print(type(y))
print(type(z))


# In[19]:


x = 1.9         #int
y = 3         # float
z = 4+1j      #complex

# convert from fioat to int :
a = int(x)

# convert from float to int :
a = int(y)

# convert from int to complex :
a = complex(z)

print(x)
print(y)
print(z)

print(type(x))
print(type(y))
print(type(z))


# In[ ]:




